### ISSUE TITLE
[RFE] Provide optional command YAML for QUADS phases using asyncio subprocess 

### ISSUE THREAD

**Issue by sadsfae** [quadsproject/quads#471]
This RFE would cover supporting an optional YAML template that lets QUADS admins define free-form commands that can be run during the M&R (move_and_rebuild) phase of QUADS or any phase of the QUADS lifecycle for an environment.  We wouldn't fail on these commands they should be best-effort, though we should log their results.

We'd define commands/actions to run in a YAML template and process them using [asyncio-driven subprocess](https://docs.python.org/3/library/asyncio-subprocess.html) calls via Python.

**Scope**

Some thought should be put into providing the ability when to run certain commands against systems, e.g. before kickstart.  To avoid over complication we might just support one or two _markers_ here like `pre_provision` and `post_provision` or even `post_release` and tag those to appropriate methods for their marker phases.

We might also want some rudimentary asyncio return status to support basic `depends` between asyncio subprocess commands.

e.g. 

```yaml
pre_provision:
  cmd_name: dell_unmount_remoteimage
    cmd:  racadm remoteimage -d

 cmd_name: check_raid_layout
   cmd: some.script.here.that.checks.disk.layout
   fatal: yes
      
post_provision:
  cmd_name: capture_lshw_info
    cmd: lshw -json > hostname.json

  cmd_name: copy lshw results
    cmd_depends: capture_lshw_info
    cmd: curl -T hostname.json ftp://ftp.example.com --user user:secret

post_release:
   cmd_name:  run jetlag to install OCP latest stable version
   cmd:  <some set of commands here>
``` 

This can be defined somewhere like `/opt/quads/conf/helper-tools.yml`

I didn't include something like `pre_release` because our `notify.py` notification library takes care of this (it already sends webhooks for release for example) but this is moreso for actions to run during pre-release phases for things that are not fatal in non-execution for processing batches of systems.

We can include an area for user-managed scripts that are referenced 

`helper_tools_location:  /opt/quads/helper-tools`

We can gate pass/fail on the various phases like `--move-hosts` or `--validate-env`

`post_release` tasks would be best-effort and beyond the scope of what we can track or resolve as it's already in tenant hands at that point.

**Some Potential Usage**

* Run some arbitrary command that helps scoot systems out easier without having to develop and ship new M&R methods e.g. `racadm remoteimage -d` to unmount virtual media (edit:  this is an example as we already do this now for Dell now too via https://github.com/redhat-performance/quads/commit/2df0e240ffc4c854e4e917c3ffe7f40f55e6875e )
* Compare system disk order/layout to what it should be and fail on it if it doesn't match.
* Offload the `lshw` hardware collection process after a machine kickstarts (while we still have access to it, but before it gets assigned to tenants)
* Run some kind of post-release automation, possibly related to https://github.com/redhat-performance/quads/issues/417
